
version: 2.1

commands:
  greeting:
      parameters:
         to:
           default: "world"
           type: string
      steps:
         - run: echo "Hello <<parameters.to>>"

  test:
    steps:
      - run: 
          name: "gotestsum install"
          command: go get gotest.tools/gotestsum
      - run: 
          name: "create test results dir"
          command: mkdir -p test-results
      - run: 
          name: "execute tests"
          command: gotestsum --format dots --junitfile test-results/unit_tests.xml ./...
      - store_test_results:
          path: test-results

jobs:
  sanity:
    docker:
      # specify the version
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/curious-kitten/forge
    steps:
      - checkout
      - test
      

workflows:
  version: 2
  test-integration:
    jobs:
      - sanity
