# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Runs unit tests
  test:
    name: "Unit tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
      
    - name: Test
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out
        go tool cover -html=coverage.out -o=report.html
    
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Coverage Report
        path: report.html

  # Runs the linter
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1


  build:
    name: Build Linux
    needs: [test, golangci]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.2

      - run: go build -o _builds/linux/forge

      - name: Executable
        uses: actions/upload-artifact@v2
        with:
          name: Linux executable
          path: _builds/linux/forge
      
      
