name: Pull Request flow

on:
  pull_request: {}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: test
      shell: bash
      run:  go test -v --short --race -json -coverprofile=coverage.out ./... > unit-test.json
    - name: annotate
      if: always()
      uses: guyarb/golang-test-annotations@v0.5.1
      with:
        test-results: unit-test.json
