name: Main Flow

on:
  push:
    branches: [main]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/test
  release:
    name: release
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
    - uses: go-semantic-release/action@v1
      id: semrel
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allow-initial-development-versions: true
        force-bump-patch-version: true
